name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux # Uncomment to build for aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU
        if: matrix.system == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            extra-platforms = aarch64-linux

      - name: Build
        run: nix build .#packages.${{ matrix.system }}.default

      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts
          cp -L result/image.tar.xz artifacts/nixos-crostini-${{ matrix.system }}-image.tar.xz
          cp -L result/metadata.tar.xz artifacts/nixos-crostini-${{ matrix.system }}-metadata.tar.xz

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nixos-crostini-${{ matrix.system }}
          path: artifacts/*
